### ISSUE TITLE
Release binaries missing for 0.1.0

### ISSUE THREAD

**Issue by alecthomas** [go-python/gpython#195]
It would be most appreciated if these could be uploaded 🙏

**Comment by c0mm4nd** [comment]
Same issue.
When importing `stdlib` 
```
        github.com/go-python/gpython/stdlib: github.com/go-python/gpython/stdlib@v0.1.1-0.20230608094744-7102b79c9ede: invalid pseudo-version: preceding tag (v0.1.0) not found
```

**Comment by sbinet** [comment]
I've just cut `v0.2.0`.
this should fix it.

**Comment by eadmaster** [comment]
i still do not see any binary with [rel v0.2.0 here](https://github.com/go-python/gpython/releases/tag/v0.2.0)
